/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *ouvrier1;
  GtkWidget *gestion_ouvrier;
  GtkWidget *affichage;
  GtkWidget *modification;
  GtkWidget *suprimer;
  GtkWidget *ajouter;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  ouvrier1 = create_ouvrier1 ();
  gtk_widget_show (ouvrier1);
  /*gestion_ouvrier = create_gestionouvrier ();
  gtk_widget_show (gestion_ouvrier);
  affichage = create_affichage ();
  gtk_widget_show (affichage);
  modification = create_modification ();
  gtk_widget_show (modification);
  suprimer = create_supprimer ();
  gtk_widget_show (suprimer);
  ajouter = create_ajouter ();
  gtk_widget_show (ajouter);*/

  gtk_main ();
  return 0;
}

